# Generated by Django 5.0 on 2023-12-13 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('house', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=20, null=True)),
                ('year_of_birth', models.IntegerField(blank=True, null=True)),
                ('wizard', models.BooleanField(null=True)),
                ('ancestry', models.CharField(blank=True, max_length=50, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=20, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=20, null=True)),
                ('patronus', models.CharField(blank=True, max_length=100, null=True)),
                ('hogwarts_student', models.BooleanField(null=True)),
                ('hogwarts_staff', models.BooleanField(null=True)),
                ('actor', models.CharField(blank=True, max_length=100, null=True)),
                ('alive', models.BooleanField(null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wood', models.CharField(max_length=50)),
                ('core', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
    ]
